[package]
name = "screen_streamer"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
warp = "0.3.7"
scrap = "0.5.0"
image = "0.25.5"
async-stream = "0.3.6"
bytes = "1.10.0"